project:
  name: quickstart-aws-acm-certificate
  owner: quickstart-eng@amazon.com
  package_lambda: true
  shorten_stack_name: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-2
  parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3Prefix: quickstart-aws-acm-certificate/
      HostedZoneID: overrride
      DomainName: override
      SubjectAlternativeNames: override
tests:
   multiregion-test:
     regions:
     - eu-north-1 # StockHolm
     - ap-south-1
     - eu-west-3
     - eu-west-2
     - eu-west-1
     - ap-northeast-2
     - ap-northeast-1
     - sa-east-1
     - ca-central-1
     - ap-southeast-1
     - ap-southeast-2
     - eu-central-1
     - us-east-1
     - us-east-2
     - us-west-2
     - ap-east-1
     - me-south-1
     template: templates/quickstart-aws-acm-certificate.template.yml
